 --- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment and start using Evolutions

 --- !Ups

create table grr_pickup_type (
  type_id                       Number(10,0) not null,
  name                          VARCHAR2(255),
  constraint pk_grr_pickup_type primary key (type_id)
);
create sequence pickup_type_id_seq;

create table grr_pickup_quantity_type (
  id                            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  quantity_name                 VARCHAR2(255),
  constraint pk_grr_pickup_quantity_type primary key (id)
);

create table grr_route (
  route_id                      Number(10,0) not null,
  route_desc                    VARCHAR2(255),
  city                          VARCHAR2(255),
  state                         VARCHAR2(255),
  zip                           VARCHAR2(255),
  enter_date                    timestamp,
  modify_date                   timestamp,
  constraint pk_grr_route primary key (route_id)
);
create sequence route_id_seq;

create table grr_route_collection (
  route_coll_id                 Number(10,0) not null,
  user_id                       VARCHAR2(255),
  route_begin_time              timestamp,
  route_end_time                timestamp,
  vehicle_id                    integer,
  route_id                      integer,
  constraint uq_grr_route_coll_vehicle_id unique (vehicle_id),
  constraint pk_grr_route_collection primary key (route_coll_id)
);
create sequence route_coll_id_seq;

create table grr_route_coll_action (
  route_coll_action_id          Number(10,0) not null,
  route_stop_order              Number(10,0),
  route_action_comment          VARCHAR2(255),
  route_action_lat              Number(15,7),
  route_action_lon              Number(15,7),
  route_stop_name               VARCHAR2(255),
  address                       VARCHAR2(255),
  contact_name                  VARCHAR2(255),
  contact_email                 VARCHAR2(255),
  notify_contact_on_next        CHAR(1),
  notify_contact_on_exception   CHAR(1),
  arrival_time                  timestamp,
  departure_time                timestamp,
  route_action_exception        VARCHAR2(255),
  pickup_item_1                 Number(10,0),
  pickup_item_1_measurement     Number(10,0),
  pickup_item_1_quantity        Number(15,7),
  pickup_item_1_weight          Number(10,0),
  pickup_item_2                 Number(10,0),
  pickup_item_2_measurement     Number(10,0),
  pickup_item_2_quantity        Number(15,7),
  pickup_item_2_weight          Number(10,0),
  pickup_item_3                 Number(10,0),
  pickup_item_3_measurement     Number(10,0),
  pickup_item_3_quantity        Number(15,7),
  pickup_item_3_weight          Number(10,0),
  route_coll_id                 Number(10,0),
  constraint uq_grr_route_coll_rte_act_exc unique (route_action_exception),
  constraint uq_grr_route_coll_act_pku_itm1 unique (pickup_item_1),
  constraint uq_grr_route_coll_pku_itm1_ms unique (pickup_item_1_measurement),
  constraint uq_grr_route_coll_act_pku_itm2 unique (pickup_item_2),
  constraint uq_grr_route_coll_pku_itm2_ms unique (pickup_item_2_measurement),
  constraint uq_grr_route_coll_act_pku_itm3 unique (pickup_item_3),
  constraint uq_grr_route_coll_pku_itm3_ms unique (pickup_item_3_measurement),
  constraint pk_grr_route_coll_action primary key (route_coll_action_id)
);
create sequence route_coll_action_id_seq;

create table grr_route_exceptions (
  route_action_exception        VARCHAR2(255) not null,
  enter_date                    timestamp,
  modify_date                   timestamp,
  constraint pk_grr_route_exceptions primary key (route_action_exception)
);

create table grr_route_stop (
  route_stop_id                 Number(10,0) not null,
  route_stop_order              integer,
  route_stop_name               VARCHAR2(255),
  street_address1               VARCHAR2(255),
  street_address2               VARCHAR2(255),
  city                          VARCHAR2(255),
  state                         VARCHAR2(255),
  zip                           VARCHAR2(255),
  contact_name                  VARCHAR2(255),
  contact_email                 VARCHAR2(255),
  notify_contact_on_next        CHAR(1),
  notify_contact_on_exception   CHAR(1),
  route_stop_lat                Number(15,7),
  route_stop_lon                Number(15,7),
  enter_date                    timestamp,
  modify_date                   timestamp,
  pickup_item_1                 Number(10,0),
  pickup_item_1_measurement     Number(10,0),
  pickup_item_2                 Number(10,0),
  pickup_item_2_measurement     Number(10,0),
  pickup_item_3                 Number(10,0),
  pickup_item_3_measurement     Number(10,0),
  route_id                      Number(10,0),
  constraint uq_grr_stop_pkup_itm1 unique (pickup_item_1),
  constraint uq_grr_stop_pkup_itm1_msre1 unique (pickup_item_1_measurement),
  constraint uq_grr_stop_pkup_itm2 unique (pickup_item_2),
  constraint uq_grr_stop_pkup_itm1_msre2 unique (pickup_item_2_measurement),
  constraint uq_grr_stop_pkup_itm3 unique (pickup_item_3),
  constraint uq_grr_stop_pkup_itm1_msre3 unique (pickup_item_3_measurement),
  constraint pk_grr_route_stop primary key (route_stop_id)
);
create sequence route_stop_id_seq;

create table grr_vehicle (
  vehicle_id                    Number(10,0) not null,
  vehicle_desc                  VARCHAR2(255),
  replacement_cost              Number(10,0),
  enter_date                    timestamp,
  modify_date                   timestamp,
  constraint pk_grr_vehicle primary key (vehicle_id)
);
create sequence vehicle_id_seq;

alter table grr_route_collection add constraint fk_grr_rte_coll_veh_id foreign key (vehicle_id) references grr_vehicle (vehicle_id);

alter table grr_route_coll_action add constraint fk_grr_rte_coll_act_rte_act_ex foreign key (route_action_exception) references grr_route_exceptions (route_action_exception);

alter table grr_route_coll_action add constraint fk_grr_rte_coll_act_pku_itm_1 foreign key (pickup_item_1) references grr_pickup_type (type_id);

alter table grr_route_coll_action add constraint fk_grr_rte_coll_act_pku_itm1_m foreign key (pickup_item_1_measurement) references grr_pickup_quantity_type (id);

alter table grr_route_coll_action add constraint fk_grr_rte_coll_act_pku_itm_2 foreign key (pickup_item_2) references grr_pickup_type (type_id);

alter table grr_route_coll_action add constraint fk_grr_rte_coll_act_pku_itm2_m foreign key (pickup_item_2_measurement) references grr_pickup_quantity_type (id);

alter table grr_route_coll_action add constraint fk_grr_rte_coll_act_pku_itm_3 foreign key (pickup_item_3) references grr_pickup_type (type_id);

alter table grr_route_coll_action add constraint fk_grr_rte_coll_act_pku_itm3_m foreign key (pickup_item_3_measurement) references grr_pickup_quantity_type (id);

alter table grr_route_coll_action add constraint fk_grr_rte_coll_act_rte_collid foreign key (route_coll_id) references grr_route_collection (route_coll_id);

 create index ix_grr_rte_coll_act_rte_collid on grr_route_coll_action (route_coll_id);

alter table grr_route_stop add constraint fk_grr_rte_stop_pku_itm1 foreign key (pickup_item_1) references grr_pickup_type (type_id);

alter table grr_route_stop add constraint fk_grr_rte_stop_pku_itm1_ms foreign key (pickup_item_1_measurement) references grr_pickup_quantity_type (id);

alter table grr_route_stop add constraint fk_grr_rte_stop_pku_itm2 foreign key (pickup_item_2) references grr_pickup_type (type_id);

alter table grr_route_stop add constraint fk_grr_rte_stop_pku_itm2_ms foreign key (pickup_item_2_measurement) references grr_pickup_quantity_type (id);

alter table grr_route_stop add constraint fk_grr_rte_stop_pku_itm3 foreign key (pickup_item_3) references grr_pickup_type (type_id);

alter table grr_route_stop add constraint fk_grr_rte_stop_pku_itm3_ms foreign key (pickup_item_3_measurement) references grr_pickup_quantity_type (id);

alter table grr_route_stop add constraint fk_grr_route_stop_route_id foreign key (route_id) references grr_route (route_id);
create index ix_grr_route_stop_route_id on grr_route_stop (route_id);


